config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :trades, only: [:show, :new, :create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password_confirmation, presence: true, length: { maximum: 50 }
    has_many :trades
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController

  def index
  end

end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :correct_user, only: %i[ show edit update destroy ]
  before_action :set_trade, only: %i[ show edit update destroy ]

  # GET /trades/1 or /trades/1.json
  def show
  end

  # GET /trades/new
  def new
    @trade = Trade.new
  end

  # GET /trades/1/edit
  def edit
  end

  # POST /trades or /trades.json
  def create
    @trade = current_user.trades.build(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: "Trade was successfully created." }
        format.json { render :show, status: :created, location: @trade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1 or /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to @trade, notice: "Trade was successfully updated." }
        format.json { render :show, status: :ok, location: @trade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1 or /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to trades_url, notice: "Trade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def correct_user
    @trades = current_user.trades.find_by(id: params[:id])
    unless @trades
      redirect_to root_url
    end
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trade_params
      params.require(:trade).permit(:entry_datetime, :entry_price, :position, :expected_profit, :expected_profit_pips, :loss_cut, :loss_cut_pips, :currency_pair, :lot, :entry_memo, :exit_datetime, :exit_price, :exit_memo, :profit_and_loss, :profit_and_loss_pips)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user_logged_in, only: [:show, :edit, :update, :destroy]

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    @trades = @user.trades.order(id: :desc)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm">
    <a class="navbar-brand" href="/">FX Trade Log</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right ul-bgcolor">
              <li class="dropdown-item"><%= link_to 'My Page', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FX Trade Log</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <script src="https://code.jquery.com/jquery-1.8.3.js"></script>
    <script src="https://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
    <script>
      $( function() {
        $( "#datepicker" ).datepicker({
          dateFormat: 'yy/mm/dd',
        });
      } );
    </script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<div class="center jumbotron">
  <div class="text-center">
    <h1>Welcome to the FX Trade Log</h1>
    <% unless logged_in? %>
      <br>
      <br>
      <%= link_to 'ユーザー新規登録', signup_path, class: 'btn btn-primary link-signup' %>
    <% end %>
</div>
</div>
<div class="text-center">
  <h2>【使い方】</h2>
  <br>
  <h5>▼以下のようにFXトレードの内容を記録し、自身のトレードを振り返り、<br>トレードの勝率を上げていきましょう！</h5>
  <br>
  <img class="mr-2 rounded" src="/assets/FXTradeLog_newlog_561x758.png" alt="トレードの記録">
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <h5>▼作成したトレード記録はMyPageからいつでも確認できます！</h5>
  <br>
  <img class="mr-2 rounded" src="/assets/FXTradeLog_mypage_576x346.png" alt="トレードの記録">
</div>

app/views/trades/_form.html.erb
<%= form_with(model: trade, local: true) do |form| %>
  <% if trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% trade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :entry_datetime, "▼エントリー日時" %>
    <%= form.datetime_select :entry_datetime %>
  </div>
  <br>
  <div class="field">
    <%= form.label :exit_datetime, "▼決済日時" %>
    <%= form.datetime_select :exit_datetime %>
  </div>
  <br>
  <div class="field">
    <%= form.label :currency_pair, "▼通貨ペア" %>
    <%= form.text_field :currency_pair %>　　
    <%= form.radio_button :position, "ロング" %>
    <%= form.label :position, "ロング　", {value: :long, style: "display: inline-block;"} %>
    <%= form.radio_button :position, "ショート" %>
    <%= form.label :position, "ショート", {value: :short, style: "display: inline-block;"} %>
  </div>

  <div class="field">
    <%= form.label :entry_price, "▼エントリーレート" %>
    <%= form.text_field :entry_price %>
  </div>
  
  <div class="field">
    <%= form.label :expected_profit, "▼利益確定予定レート" %>
    <%= form.text_field :expected_profit %>（※レート入力）　　　
    <%= form.text_field :expected_profit_pips %>　pips
  </div>

  <div class="field">
  </div>

  <div class="field">
    <%= form.label :loss_cut, "▼損切予定レート" %>
    <%= form.text_field :loss_cut %>（※レート入力）　　　
    <%= form.text_field :loss_cut_pips %>　pips
  </div>

  <div class="field">
    <%= form.label :lot, "▼取引数量（lot）" %>
    <%= form.text_field :lot %>　万通貨
  </div>

  <div class="field">
    <%= form.label :entry_memo, "▼エントリー時の分析内容" %>
    <%= form.text_area :entry_memo, size: "70x5" %>
  </div>

  <div class="field">
    <%= form.label :exit_price, "▼決済レート" %>
    <%= form.text_field :exit_price %>
  </div>

  <div class="field">
    <%= form.label :profit_and_loss, "▼損益" %>
    <%= form.text_field :profit_and_loss %>　円　　　
    <%= form.text_field :profit_and_loss_pips %>　pips
  </div>

  <div class="field text-block">
    <%= form.label :exit_memo, "▼取引振り返り" %>
    <%= form.text_area :exit_memo, size: "70x5" %>
  </div>

  <div class"actions row">
    <%= form.submit '作成', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h2>[トレードログ修正]</h2>

<%= render 'form', trade: @trade %>
<br>
<%= link_to '戻る', @trade %>

app/views/trades/new.html.erb
<h2>[トレードログ新規作成]</h2>

<%= render 'form', trade: @trade %>

<br>
<%= link_to 'My Pageに戻る', user_path(current_user) %>

app/views/trades/show.html.erb
<h3>[トレード内容]</h3>
<table border="2">

  <tr><th>エントリー日時</th><td><%= @trade.entry_datetime %></td></tr>

  <tr><th>決済日時</th><td><%= @trade.exit_datetime %></td></tr>

  <tr><th>通貨ペア（ポジション）</th><td><%= @trade.currency_pair %>（<%= @trade.position %>）</td></tr>

  <tr><th>エントリーレート</th><td><%= @trade.entry_price %></td></tr>

  <tr><th>利益確定予定レート</th><td><%= @trade.expected_profit %>（<%= @trade.expected_profit_pips %>pips）</td></tr>

  <tr><th>損切予定レート</th><td><%= @trade.loss_cut %>（<%= @trade.loss_cut_pips %>pips）</td></tr>

  <tr><th>取引数量（lot）</th><td><%= @trade.lot %>万通貨</td></tr>

  <tr><th>エントリー時の分析内容</th><td><%= @trade.entry_memo %></td></tr>

  <tr><th>決済レート</th><td><%= @trade.exit_price %></td></tr>
  <tr><th>損益</th><td> <%= @trade.profit_and_loss %>円（<%= @trade.profit_and_loss_pips %>pips）</td></tr>
  <tr><th>取引振り返り</th><td><%= @trade.exit_memo %></td></tr>

</table>
<br>
<div>
  <%= link_to '修正する', edit_trade_path(@trade) %>
</div>
<div>
  <%= link_to 'My Pageトップへ', user_path(current_user) %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'Name：' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email, 'Email：' %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'Password：' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'Password Confirmation：' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
 <h1>ユーザー情報変更</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

  <%= render 'form', user: @user %>

  <br>
  <%= link_to 'My Pageに戻る', @user %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
 <h1>ユーザー情報登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

  <%= render 'form', user: @user %>

  <br>
  <div class="text-center">※すでにアカウントをお持ちの方は<%= link_to 'こちら', login_path%>
 </div>
</div>

app/views/users/show.html.erb
<h2>ユーザー情報</h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name：</strong><%= @user.name %>
</p>

<p>
  <strong>Email：</strong>
  <%= @user.email %>
</p>

<p>
<%= link_to '登録情報変更', edit_user_path(@user), class: 'btn btn-primary'  %>
</p>

<br>
<br>

<h2>FXトレードログ</h2>
<p>
<%= link_to 'ログ新規作成', new_trade_path(), class: 'btn btn-primary'  %>
</p>

<ul>
  <% @trades.each do |trade| %>
    <% linkstr = trade.entry_datetime.to_s + '（' + trade.currency_pair.to_s + '）' %>
    <li><%= link_to linkstr, trade_path(trade.id) %></li>
  <% end %>
</ul>